import 'package:cupertino_onboarding/cupertino_onboarding.dart';
import 'package:flutter/cupertino.dart';
import 'package:persistent_bottom_nav_bar/persistent_tab_view.dart';
import 'package:provider/provider.dart';
import 'package:quiz_app/models/question_single_choice.dart';
import 'package:quiz_app/models/quiz.dart';
import 'package:quiz_app/screens/quiz/questions_screen.dart';
import 'package:quiz_app/viewmodels/quiz.viewmodel.dart';

import '../../models/iquestion.dart';
import '../../viewmodels/user.viewmodel.dart';

class AIQuizStartScreen extends StatefulWidget {
  final Quiz quiz;
  bool runOnce;

  AIQuizStartScreen({super.key, required this.quiz, this.runOnce = false});

  @override
  State<AIQuizStartScreen> createState() => _AIQuizStartScreenState();
}

class _AIQuizStartScreenState extends State<AIQuizStartScreen> {
  late List<IQuestion> allQuestions;

  @override
  initState() {
    super.initState();
    readData(context.read<QuizViewModel>()).then((value) {
      setState(() {
        allQuestions = value;
      });
    });
  }

  Future<List<IQuestion>> readData(QuizViewModel quizData) async {
    await context.read<QuizViewModel>().getQuestionsFromQuiz(widget.quiz);

    List<IQuestion> allQuestions = [];

    List<QuestionSingleChoice> questions = quizData.questions;
    questions.shuffle();

    final questionsMatcher = quizData.questionsMatcher;

    if (widget.runOnce == false) {
      for (var i = 0; i < questions.length; i++) {
        var correctNumberIndex = questions[i].correctAnswerIndex;
        var correctAnswer = questions[i].answers[correctNumberIndex];
        questions[i].answers.shuffle();
        questions[i].correctAnswerIndex =
            questions[i].answers.indexOf(correctAnswer);
      }
      widget.runOnce = true;
    }

    for (var i = 0; i < questions.length; i++) {
      print(questions[i].answers.toString());
      allQuestions.add(questions[i]);
      if (i < questionsMatcher.length) {
        allQuestions.add(questionsMatcher[i]);
      }
    }

    allQuestions = allQuestions.reversed.toList();
    return allQuestions;
  }

  @override
  Widget build(BuildContext context) {
    return Consumer<QuizViewModel>(builder: (context, quizData, child) {
      return CupertinoOnboarding(
          bottomButtonBorderRadius: BorderRadius.lerp(
            BorderRadius.circular(10),
            BorderRadius.circular(20),
            10,
          ),
          bottomButtonChild: Text(
              'Start Level ${context.watch<UserViewModel>().userData?.level}'),
          bottomButtonColor: CupertinoColors.systemRed.resolveFrom(context),
          onPressedOnLastPage: () => {
                quizData.resetQuiz(),
                PersistentNavBarNavigator.pushNewScreen(
                  context,
                  screen: QuestionsScreen(allQuestions: allQuestions),
                  withNavBar: true, // OPTIONAL VALUE. True by default.
                  pageTransitionAnimation: PageTransitionAnimation.slideUp,
                )
              },
          pages: [
            WhatsNewPage(
                // scrollPhysics: const BouncingScrollPhysics(),
                title: Text(context.watch<QuizViewModel>().quizLevelTitle),
                features: [
                  // Feature's type must be `WhatsNewFeature`
                  WhatsNewFeature(
                    icon: Icon(
                      CupertinoIcons.question_circle,
                      color: CupertinoColors.systemRed.resolveFrom(context),
                    ),
                    title: const Text('Read the questions and answer'),
                    description: const Text(
                      'Answer the questions and see if you got them right!',
                    ),
                  ),
                  // tell user they are ai generated
                  WhatsNewFeature(
                    icon: Icon(
                      CupertinoIcons.bolt_fill,
                      color: CupertinoColors.systemRed.resolveFrom(context),
                    ),
                    title: const Text('AI Generated'),
                    description: const Text(
                      'These questions are generated by AI and are unique to you!',
                    ),
                  ),
                ])
          ]);
    });
  }
}
