// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb99Tt0rc00_jRflGCtEk-fkX-KiFWyKI',
    appId: '1:94245567496:web:e4bb19b6d73f93dd75e5bd',
    messagingSenderId: '94245567496',
    projectId: 'quizapp-a8f48',
    authDomain: 'quizapp-a8f48.firebaseapp.com',
    storageBucket: 'quizapp-a8f48.appspot.com',
    measurementId: 'G-QP9D805RS3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC7drc2URdajJ-Tits3vKYS3ZfMjRrQE4',
    appId: '1:94245567496:android:ac7ac0f6dab7c4ee75e5bd',
    messagingSenderId: '94245567496',
    projectId: 'quizapp-a8f48',
    storageBucket: 'quizapp-a8f48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxWS9vZwuXdARTYm8tlxN25gl0bu70VTM',
    appId: '1:94245567496:ios:bac0da1f17d9b62775e5bd',
    messagingSenderId: '94245567496',
    projectId: 'quizapp-a8f48',
    storageBucket: 'quizapp-a8f48.appspot.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxWS9vZwuXdARTYm8tlxN25gl0bu70VTM',
    appId: '1:94245567496:ios:2f727c8144e3449f75e5bd',
    messagingSenderId: '94245567496',
    projectId: 'quizapp-a8f48',
    storageBucket: 'quizapp-a8f48.appspot.com',
    iosBundleId: 'com.example.quizApp.RunnerTests',
  );
}
